version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${CONTAINER_CODE_PATH_HOST}
      - ${NGINX_VHOSTS_PATH}:/etc/nginx/conf.d
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${NGINX_LOG_PATH}:/var/log/nginx
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "20"
    networks:
      - net-go

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:4.0
    networks:
      - net-redis
    volumes:
      - "${REDIS_DATA_DIR}:/data"
    ports:
      - "${REDIS_PORT}:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    networks:
      - net-mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    networks:
      - net-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      -
  go-api:
    build:
      context: ./go/go-api
    ports:
      - "9001:8000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ${GO_API_LOGS_DIR}:/temp/logs
      - ${GO_API_CONF_FILE}:/config
    restart: always
    networks:
      - net-go
      - net-mysql
      - net-redis

networks:
  net-mysql:
  net-redis:
  net-go:
